name: ng_mediaquery
description: A Angular 2 directive that can be used to data bind to a CSS media query.
version: 0.1.0
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.0
dev_dependencies:
  browser: ^0.10.0